name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the specified branches
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: ./client
        
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Sets up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
           node-version: 14
           
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Runs a set of commands using the runners shell
      - name: Install dependencies and build project
        run: |
          npm install,
          npm run build

  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      
      - name: Run tests, linter, and formatter
        run: npm run quality-check
